development:
  adapter: postgresql
  encoding: unicode
  database: permits_dev

test:
  adapter: postgresql
  encoding: unicode
  database: permits_test

production:
  adapter: postgresql
  encoding: unicode
  database: permits_test

